### ISSUE TITLE
further explination on how to apply patch

### ISSUE THREAD

**Issue by tomlevavisar** [tprelog/prusa_files#1]
hey, kind of a noob software wise. what do i do to apply the patch to the printer? and what steps fo i need to take? thanks

**Comment by tomlevavisar** [comment]
also, is this compatible with the mmmy2s or do i need to do something with the file

**Comment by tprelog** [comment]
Hi @tomlevavisar,

The _patch_ is applied to the firmware source code, which must also be download from [Prusa's GitHub Page](https://github.com/prusa3d/Prusa-Firmware/releases), then compiled. The instructions for Linux are in the README. 

If you do not need to make additional changes, then these instructions are basically copy and paste. Lines beginning with a `#` are comments. Each comment briefly explains what the commands are doing for each step

```
# create an empty directory and `cd` into it
mkdir fw_391
cd fw_391

# download and extract the source code for prusa firmware
wget -O Prusa-Firmware-3.9.1.zip https://github.com/prusa3d/Prusa-Firmware/archive/v3.9.1.zip
unzip Prusa-Firmware-3.9.1.zip

# `cd` into unzipped directory and download the skelestrude fw patch
cd Prusa-Firmware-3.9.1
wget -O skelestruder-3.9.1.patch https://raw.githubusercontent.com/tprelog/prusa_files/master/fw_patch_files/skelestruder-3.9.1.patch

# apply the skelestruder patch to the prusa firmware
patch -p1 < skelestruder-3.9.1.patch

# compile skelestruder firmware for prusa mk3s
./PF-build.sh 1_75mm_MK3S-EINSy10a-E3Dv6full.h EN_ONLY GOLD

# flash firmware using prusa slic3r or octoprint firmware-updater -- profit!
```

I'm sorry if you use Windows, I don't so I can't help with that.

- Yes, this should work with MMU2S. 
- If you are using MK3S -  (and English only firmware is OK) you can just [download a pre-compiled version](https://github.com/tprelog/prusa_files/tree/master/skelestruder_fw/mk3s_3.9.1)


The compiled firmware is flashed to the printer like normal...
- [flash firmware using prusa slic3r](https://help.prusa3d.com/en/article/firmware-updating-and-flashing_2227)


EDIT: I'll update the README, combining the basic steps with the additional notes, so that it might be more clear when to make your own changes.

**Comment by tomlevavisar** [comment]
Thanks for the response! Is there a way to do this on windows?


TOM LEV AVISAR // IT MANAGER

Office: 44.20.3808.9262
Mobile: +972.50.3409081

playermaker.com

**Comment by tomlevavisar** [comment]
Do I just flash the precompiled firmware then I'm good to go?


TOM LEV AVISAR // IT MANAGER

Office: 44.20.3808.9262
Mobile: +972.50.3409081

playermaker.com

**Comment by tprelog** [comment]
> Is there a way to do this on windows?

Sorry I don' t use Windows so I really don't know - One option, I think you could use the Linux Subsystem thing available in Windows - I'm really not sure though. I stopped using Windows over 10 years ago



> Do I just flash the precompiled firmware then I'm good to go

**IF** you have MK3S **AND** English only firmware is ok, then yes, you can just use my pre-compiled version

**Comment by tomlevavisar** [comment]
thanks! my printer is a mk3s in enlgish so i just flashed the firmware you have compiled! one last question is what filament sensor are you using and wil it work with the mmu2s ir sensor? thanks alot!

**Comment by tprelog** [comment]
I think I'm using the new IR Sensor -- I have them both, the old sensor had four wires - I'm using the new sensor with 3 wires.

For the MMU2S, The sensor I'm using works with the SP_IR_xxx_BETA2 parts listed here: https://www.thingiverse.com/thing:3255143

**EDIT**: Also, when reading the thing details for the MMU2 parts, it says
>You will also want to make a simple change to firmware:

The firmware changes listed there, have already been included here :slightly_smiling_face:

**Comment by tomlevavisar** [comment]
Thanks! So it's perfect for me! Saved me alot of time and a headache :)
